// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2DczRa451ljBNBVXBnIikW9cOFncBLGc',
    appId: '1:899039557300:web:00f144833e012fb4f6c9e1',
    messagingSenderId: '899039557300',
    projectId: 'plant-a4646',
    authDomain: 'plant-a4646.firebaseapp.com',
    storageBucket: 'plant-a4646.firebasestorage.app',
    measurementId: 'G-V39T0N724D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQWqOKgqDStHHMrkDT4wH2Wbo4eH_IqJQ',
    appId: '1:899039557300:android:4e1a1253b8b2e736f6c9e1',
    messagingSenderId: '899039557300',
    projectId: 'plant-a4646',
    storageBucket: 'plant-a4646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT1MxkCzoG0fhJ5D0qsV-_M8ce_9cH_fM',
    appId: '1:899039557300:ios:73ff8ad3f1696861f6c9e1',
    messagingSenderId: '899039557300',
    projectId: 'plant-a4646',
    storageBucket: 'plant-a4646.firebasestorage.app',
    iosClientId: '899039557300-nbaccgok2q46ibov57piqkpt7n2d5p1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisanIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT1MxkCzoG0fhJ5D0qsV-_M8ce_9cH_fM',
    appId: '1:899039557300:ios:73ff8ad3f1696861f6c9e1',
    messagingSenderId: '899039557300',
    projectId: 'plant-a4646',
    storageBucket: 'plant-a4646.firebasestorage.app',
    iosClientId: '899039557300-nbaccgok2q46ibov57piqkpt7n2d5p1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisanIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2DczRa451ljBNBVXBnIikW9cOFncBLGc',
    appId: '1:899039557300:web:2dc73f776f534c88f6c9e1',
    messagingSenderId: '899039557300',
    projectId: 'plant-a4646',
    authDomain: 'plant-a4646.firebaseapp.com',
    storageBucket: 'plant-a4646.firebasestorage.app',
    measurementId: 'G-PCR3W08CTH',
  );
}
